Repository githubschool/stem, pull requests merged in 2020-10, with the labels that each got.

#10 Edit caption to be more descriptive
  _slides/02-ericalloyd.md
Labels: caption-update-project

#14 Edit Caption to say MEEEOOOW
  _slides/12-stevenvelasquez.md
Labels: caption-update-project

#11 Edit caption to be more descriptive
  _slides/17-auharrison-clgx.md
Labels: ah-caption-update-project

#15 Edit caption
  _slides/08-prasobhHERE.md
Labels: caption-update-project

#13 Edit caption to be more descriptive
  _slides/11-shahim22.md
Labels: My-caption-project

#18 Aneesh Caption Changed for test
  _slides/16-akkp-cts.md
Labels: aneesh-caption-prj
